# Generated by Django 5.0.4 on 2024-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnAModel',
            fields=[
                ('Question_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Questions', models.TextField()),
                ('Answers', models.TextField()),
            ],
        ),
    ]
